name: ais-adsb-cot

services:
  cotmultitargets:
    image: kanzuke/cot-multi-targets:latest
    container_name: cotmultitargets
    restart: unless-stopped
    network_mode: "host"
    environment:
      - TZ=Etc/UTC
      - COT_MULTI_PORT=9090
      - COT_DEBUG=false
    volumes:
      - ./cot-multi-targets/config.json:/app/config.json:ro


  cotproxyweb:
    image: kanzuke/cotproxyweb:latest
    container_name: cotproxyweb
    restart: unless-stopped
    network_mode: "host"
    environment:
      - TZ=Etc/UTC
      - DJANGO_ALLOWED_HOSTS=0.0.0.0
      - ADMIN_USER=admin
      - ADMIN_PASSWORD=admin

  cotproxy:
    image: kanzuke/cotproxy:latest
    container_name: cotproxy
    restart: unless-stopped
    depends_on:
      - cotmultitargets
      - cotproxyweb
    network_mode: "host"
    environment:
      - TZ=Etc/UTC
      - COT_LISTEN_URL=udp://0.0.0.0:8087
      - COT_FORWARD_URL=tcp://127.0.0.1:9090
      - PASS_ALL=True
      - AUTO_ADD=True
      - SEED_FAA_REG=True

  adsbcot:
    image: kanzuke/adsbcot:latest
    container_name: adsbcot
    restart: unless-stopped
    depends_on:
      - cotproxy
    network_mode: "host"
    environment:
      - TZ=Etc/UTC
      - ADSB_FEED_URL=http://127.0.0.1:8080/data/aircraft.json
      - ADSB_POLL_INTERVAL=5
      - COT_URL=udp+wo://127.0.0.1:8087
    volumes:
      - ./adsbcot/known_aircraft.csv:/app/known_aircraft.csv:ro
    
  aiscot:
    image: kanzuke/aiscot:latest
    container_name: aiscot
    restart: unless-stopped
    depends_on:
      - cotproxy
    network_mode: "host"
    environment:
      - TZ=Etc/UTC
      - AIS_PORT=5050
      - COT_URL=udp+wo://127.0.0.1:8087
    volumes:
      - ./aiscot/ais-known-craft.csv:/app/ais-known-craft.csv
